### ISSUE TITLE
It will report  RuntimeError when it run under multithreading

### ISSUE THREAD

**Issue by rolemee** [guofei9987/blind_watermark#103]
```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rolemee/.local/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/home/rolemee/.local/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/rolemee/.local/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/rolemee/.local/lib/python3.10/site-packages/uvicorn/config.py", line 477, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/rolemee/.local/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rolemee/work/outsourcing/BlindWatermark/app/./main.py", line 4, in <module>
    from blind_watermark import WaterMark
  File "/home/rolemee/.local/lib/python3.10/site-packages/blind_watermark/__init__.py", line 1, in <module>
    from .blind_watermark import WaterMark
  File "/home/rolemee/.local/lib/python3.10/site-packages/blind_watermark/blind_watermark.py", line 10, in <module>
    from .bwm_core import WaterMarkCore
  File "/home/rolemee/.local/lib/python3.10/site-packages/blind_watermark/bwm_core.py", line 11, in <module>
    from .pool import AutoPool
  File "/home/rolemee/.local/lib/python3.10/site-packages/blind_watermark/pool.py", line 6, in <module>
    multiprocessing.set_start_method('fork')
  File "/usr/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

**Comment by guofei9987** [comment]
It seems work well on my macOS and Linux. 
See this: https://github.com/guofei9987/blind_watermark/blob/master/examples/example_str_multi.py

Pls show me your code and environments.

**Comment by rolemee** [comment]
sorry,i made a mistake
