### ISSUE TITLE
请问源图片有什么要求？有些图片用文字水印解不出来，或者解出来是乱码

### ISSUE THREAD

**Issue by 21jhf** [guofei9987/blind_watermark#14]
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['E:\\ygSoft\\blindWaterMark\\blind_watermark-master', 'E:/ygSoft/blindWaterMark/blind_watermark-master'])
PyDev console: starting.
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
runfile('E:/ygSoft/blindWaterMark/blind_watermark-master/examples/origin_str.py', wdir='E:/ygSoft/blindWaterMark/blind_watermark-master/examples')
Put down the length of wm_bit 239
239
xAET
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "E:\pycharm2020.3.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "E:\pycharm2020.3.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/ygSoft/blindWaterMark/blind_watermark-master/examples/origin_str.py", line 21, in <module>
    assert wm == wm_extract, '提取水印和原水印不一致'
AssertionError: 提取水印和原水印不一致
![1010](https://user-images.githubusercontent.com/9279965/107202951-beb0c980-6a35-11eb-8e60-9de003a8c76f.png)

**Comment by creboy** [comment]
纯白底的好像有问题
