### ISSUE TITLE
截图之后保存，解析报错

### ISSUE THREAD

**Issue by a289459798** [guofei9987/blind_watermark#49]
Traceback (most recent call last):
  File "unwm.py", line 4, in <module>
    print(bwm.extract('output/test4.png', wm_shape=96, mode='str'))
  File "/Library/Python/3.8/site-packages/blind_watermark/blind_watermark.py", line 73, in extract
    wm = bytes.fromhex(hex(int(byte, base=2))[2:]).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 2: invalid start byte

**Comment by guofei9987** [comment]
see it here https://github.com/guofei9987/blind_watermark/blob/b5ad80c1f38f01b0ed70e42f584f5a597ae6797c/examples/example_str.py#L38
