### ISSUE TITLE
py3有版本的兼容问题

### ISSUE THREAD

**Issue by botsphp** [guofei9987/blind_watermark#6]
Python 3.7.0

```
Traceback (most recent call last):
  File "origin.py", line 9, in <module>
    bwm1.embed('output/打上水印的图.png')
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/blind_watermark/blind_watermark.py", line 98, in embed
    self.idx_shuffle = np.random.RandomState(self.password_img) \
AttributeError: 'mtrand.RandomState' object has no attribute 'random'
```

**Comment by guofei9987** [comment]
是不是numpy版本太低，我的 Python 3.7.6 是可以的

**Comment by botsphp** [comment]
在requirements.txt中，明确一下版本吧，我刚刚试了一下1.17是可以的。

`numpy===1.17.0`

**Comment by guofei9987** [comment]
> 在requirements.txt中，明确一下版本吧，我刚刚试了一下1.17是可以的。
> 
> `numpy===1.17.0`

感谢建议，十分合理

**Comment by guofei9987** [comment]
另外欢迎 pr
