### ISSUE TITLE
String WaterMark -- ValueError: non-hexadecimal number found in fromhex() arg at position 9

### ISSUE THREAD

**Issue by JohnTian** [guofei9987/blind_watermark#9]
```
(yolov5) ➜  BlindWatermark python
Python 3.7.9 (default, Aug 18 2020, 06:22:45) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
(yolov5) ➜  BlindWatermark pip list | grep blind
blind-watermark        0.0.6
(yolov5) ➜  BlindWatermark pip list | grep PyWavelets
PyWavelets             1.1.1
(yolov5) ➜  BlindWatermark cat demo.py 
import argparse
from blind_watermark import WaterMark


if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-in", "--imagePath", type=str, help="the path of source image.")
    parser.add_argument("-wm", "--waterMark", type=str, default='@guofei9987 开源万岁！', help="the string of watermark.")
    parser.add_argument("-ou", "--imageOutPath", type=str, help="the path of output image.")

    args = parser.parse_args()
    im_path = args.imagePath
    wm_strs = args.waterMark
    im_out_path = args.imageOutPath

    bwm1 = WaterMark(password_img=1, password_wm=1)
    bwm1.read_img(im_path)
    bwm1.read_wm(wm_strs, mode='str')
    bwm1.embed(im_out_path)
    len_wm = len(bwm1.wm_bit)
    print('Embed water mark: {}'.format(wm_strs))
    print('Put down the length of wm_bit {len_wm}'.format(len_wm=len_wm))

    wm_extract = bwm1.extract(im_out_path, wm_shape=len_wm, mode='str')
    print('Extract water mark: {}'.format(wm_extract))
(yolov5) ➜  BlindWatermark python demo.py -in K9290200015200921002_-1_crop.jpg -wm "epbox.cn" -ou K9290200015200921002_-1_crop_embed.jpg
Embed water mark: epbox.cn
Put down the length of wm_bit 63
Traceback (most recent call last):
  File "demo.py", line 24, in <module>
    wm_extract = bwm1.extract(im_out_path, wm_shape=len_wm, mode='str')
  File "/home/tianzx/.virtualenvs/yolov5/lib/python3.7/site-packages/blind_watermark/blind_watermark.py", line 165, in extract
    wm = bytes.fromhex(hex(int(byte, base=2))[2:]).decode('utf-8')
ValueError: non-hexadecimal number found in fromhex() arg at position 9
```

**Comment by JohnTian** [comment]
```
(yolov5) ➜  BlindWatermark python demo.py -in K9290200015200921002_-1_crop.jpg -ou K9290200015200921002_-1_crop_embed.jpg 
Embed water mark: @guofei9987 开源万岁！
Put down the length of wm_bit 215
Traceback (most recent call last):
  File "demo.py", line 25, in <module>
    wm_extract = bwm1.extract(im_out_path, wm_shape=len_wm, mode='str')
  File "/home/tianzx/.virtualenvs/yolov5/lib/python3.7/site-packages/blind_watermark/blind_watermark.py", line 165, in extract
    wm = bytes.fromhex(hex(int(byte, base=2))[2:]).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 14: invalid start byte

```

**Comment by guofei9987** [comment]
We updated the algorithm to enhance its robustness in version 0.2.1
